[project]
name = "inference"
version = "0.1.0"
description = "ASL Fingerspelling Recognition Inference Service"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.118.0",
    "numpy>=2.3.3",
    "pydantic>=2.11.9",
    "tensorflow>=2.20.0",
    "uvicorn>=0.37.0",
]
